[package]
name = "fahrenheit"
version = "4.5.4"
authors = ["plhk"]
description = "toy futures executor (formerly known as toykio)"
license = "MIT"
readme = "README.md"
homepage = "https://github.com/polachok/fahrenheit"
repository = "https://github.com/polachok/fahrenheit"
keywords = ["async", "futures"]
categories = ["network-programming"]
edition = "2018"

[dependencies]
futures-core = "0.3"
futures-io = "0.3"
futures-task = "0.3"
libc = "0.2"
log = "0.4"
pretty_env_logger = "0.2"
mio = {version="0.7.0-alpha.1", features = ["os-poll", "tcp"]}

[dev-dependencies]
futures = "0.3"
